name: Deploy to DigitalOcean

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/apps/NAS-Mad-BE/hr_assistant
          git pull
          source venv/bin/activate
          pip install -r requirements.txt
          sudo supervisorctl restart hr-assistant